#!/usr/bin/env sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx|css|md|json|mjs|cjs|yml|yaml)$')

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

echo "$STAGED_FILES" | xargs npx prettier --write
echo "$STAGED_FILES" | xargs git add

